# This is a basic workflow to help you get started with Actions

name: react deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - uses: borales/actions-yarn@v2.0.0
        with:
         cmd: install   
      - name: Run surge
        run: npm install --global surge
      - name: Deploy surge 
        run: surge ./ munnareact.surge.sh --token ${{ secrets.SURGE_TOKEN }}
